spring:
  application:
    name: "order-service"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_CLUSTER_URL}/${DATABASE_NAME}?${DATABASE_CLUSTER_PARAMETERS}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    hikari:
      minimum-idle: ${HIKARI_MIN_IDLE_SIZE}
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE}
  liquibase:
    enabled: ${LIQUIBASE_ENABLED}
    change-log: classpath:db/changelog/changelog-master.xml